---
- name: Repository Key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/google.asc
    mode: "0644"
    checksum: 'sha256:aa26cfdf2640ea1e02e8959b77957491cf5fb78964f06a5921e2c79607872797' # curl -sL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sha256sum
  become: true

- name: Repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/google.asc] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    filename: gcp
  become: true

- name: Install
  ansible.builtin.package:
    name:
      - google-cloud-cli
    state: latest
  become: true
