---
- name: Check current i3 version
  ansible.builtin.command:
    cmd: bash -c "/usr/bin/i3 --version | cut -d' ' -f3"
  ignore_errors: true
  register: current_i3_version
  changed_when: false

- name: Continue only when i3 is older
  ansible.builtin.fail:
    msg: "Version already exists"
  when: current_i3_version.stdout != "" and current_i3_version.stdout is ansible.builtin.version(i3_version, operator='ge', strict=True)
  register: version_changed
  ignore_errors: true

- name: Install apt packages
  ansible.builtin.apt:
    state: present
    name:
      - libxcb1-dev
      - libxcb-keysyms1-dev
      - libxcb-util0-dev
      - libxcb-icccm4-dev
      - libyajl-dev
      - libstartup-notification0-dev
      - libxcb-randr0-dev
      - libev-dev
      - libxcb-xinerama0-dev
      - libpango1.0-dev
      - libxcursor-dev
      - libxcb-cursor-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libxcb-shape0-dev
      - libxcb-xrm-dev
      - meson
      - ninja-build
  when: version_changed is succeeded
  become: true

- name: "Git clone i3 v{{ i3_version }}"
  ansible.builtin.git:
    repo: https://github.com/i3/i3.git
    dest: /opt/i3
    version: "{{ i3_version }}"
  when: version_changed is succeeded
  become: true

- name: Compile i3
  ansible.builtin.shell: >
    mason build && \
    cd build && \
    ninja && \
    ninja install
  args:
    chdir: /opt/i3
  changed_when: false
  when: version_changed is succeeded
  become: true

- name: Copy .desktop files
  ansible.builtin.shell: >
    [ -d /usr/share/xsessions/ ] && cp *.desktop /usr/share/xsessions/
  args:
    chdir: /opt/i3/share/xsessions
  changed_when: false
  when: version_changed is succeeded
  register: desktop_cp
  failed_when: desktop_cp.rc >= 2
  become: true
