---
- name: Get stat of GPG key
  ansible.builtin.stat:
    path: /usr/share/keyrings/google-chrome.gpg
  register: gpg_file

- name: Creating temp directory
  ansible.builtin.tempfile:
    state: directory
    prefix: "google-chrome"
  when: not gpg_file.stat.exists
  register: temp_dir

- name: Repository key
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: "{{ temp_dir.path }}/google-chrome.pub"
    mode: "0644"
    checksum: 'sha256:fb8df9740df6a1125fd2983465d830b764b63cd92d5ada8b5bbf75927d6a71ee'
  when: not gpg_file.stat.exists
  become: true

- name: De-Armor GPG key
  ansible.builtin.command:
    cmd: "gpg -o /usr/share/keyrings/google-chrome.gpg --dearmor {{ temp_dir.path }}/google-chrome.pub"
    creates: /usr/share/keyrings/google-chrome.gpg
  when: not gpg_file.stat.exists
  become: true

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main
    codename: "{{ dist_override | default(ansible_distribution_release) }}"
    state: present
    filename: google-chrome
    update_cache: true
    mode: "0644"
    validate_certs: true
  become: true

- name: Install Google Chrome stable
  ansible.builtin.apt:
    name:
      - google-chrome-stable
    state: present
  become: true
