---
- name: install fd-find
  ansible.builtin.apt: name=fd-find
  become: true

- name: create symlink /usr/local/bin/fd -> /usr/bin/fdfind
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    state: link
  become: true

